<?php
/**
 * @file
 * This module allows to add subscription form.
 */

module_load_include('inc', 'd7_pets_registration', 'd7_pets_registration');
module_load_include('inc', 'd7_pets_registration', 'd7_pets_registration.form');
module_load_include('inc', 'd7_pets_registration', 'd7_pets_registration.pages');

/**
 * Implements hook_menu().
 */
function d7_pets_registration_menu() {
  $items = [];

  $items['d7_pets_menu/d7_pets_registration'] = [
    'title' => 'Pets registration',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['d7_pets_owners_update_form'],
    'access arguments' => ['access d7_pets_registration content'],
    'type' => MENU_LOCAL_TASK
  ];

  $items['d7_pets_menu/d7_pets_owners_table'] = [
    'title' => 'Table with pets owners data.',
    'page callback' => 'd7_pets_owners_table_page',
    'access arguments' => ['administer site configuration'],
    'type' => MENU_LOCAL_TASK
  ];

  $items['d7_pets_owners/%id/delete'] = [
    'title callback' => 'd7_pets_owners_delete_page_title',
    'title arguments' => [1],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['d7_pets_owners_delete_form', 1],
    'access arguments' => ['administer site configuration'],
  ];

  $items['d7_pets_owners/%id/update'] = [
    'title callback' => 'd7_pets_owners_update_page_title',
    'title arguments' => [1],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['d7_pets_owners_update_form', 1],
    'access arguments' => ['administer site configuration'],
  ];
  $items['d7_pets_menu'] = [
    'title' => 'Pets owners menu',
    'page callback' => 'd7_pets_menu_callback',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  ];

  $items['d7_pets_registration_color'] = [
    'title' => 'Pets owners menu change color',
    'page callback' => 'd7_pets_registration_ajax_menu_callback',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'delivery callback' => 'ajax_deliver',
  ];

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function d7_pets_registration_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_permission().
 */
function d7_pets_registration_permission() {
  return array(
    'access d7_pets_registration content' => [
      'title' => t('Access content for the D7 Pets Registration posts module'),
    ]
  );
}

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 */
function d7_pets_registration_help($path, $arg) {
  switch ($path) {
    case "admin/help#d7_pets_registration":
      return t("Allows to add d7 Pets Registration form");
      break;
  }
}

/**
 * Implements of hook_views_api().
 */
function d7_pets_registration_views_api() {
  return array('api' => 3);
}

/**
 * Implements hook_flush_caches().
 */
function d7_pets_registration_flush_caches() {
  return array('cache_d7_pets_registration');
}

/**
* Implements hook_cron_queue_info().
*/
function d7_pets_registration_cron_queue_info() {
  $queues['d7_pets_registration_insert'] = [
    'worker callback' => 'd7_pets_registration_insert',
    'time' => 180,
  ];
  $queues['d7_pets_registration_update'] = [
    'worker callback' => 'd7_pets_registration_update',
    'time' => 180,
  ];
  return $queues;
}

