<?php
/**
 * @file
 * This module allows to add subscription form.
 */

/**
 * Implements hook_menu().
 */
function subscription_menu() {
  $items = array();

  $items['examples/subscription'] = array(
    'title' => 'Subscription',
    'description' => 'A form to subscribe.',
    'file' => 'd7_create_form.inc',
    'file path' => 'sites/all/modules/custom/subscription/includes',
    'page callback' => 'd7_create_form',
    'page arguments' => array('subscription_form'),
    'access arguments' => array('access subscription content')
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function subscription_permission() {
  return array(
    'access subscription content' => array(
      'title' => t('Access content for the Subscription posts module'),
    )
  );
}

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 */
function subscription_help($path, $arg) {
  switch ($path) {
    case "admin/help#subscription":
      return '' . t("Allows to add subscription form") . '';
      break;
  }
}

/**
 * Implements hook_form().
 *
 * Creates form for subscription.
 */
function subscription_form($form, &$form_state) {

  $form['userName'] = array(
    '#type' => 'textfield',
    '#title' => t('What is your login?'),
    '#size' => 20,
    '#maxlength' => 20,
    '#rules' => array(
      array(
        'rule' => 'regexp[/^[a-zA-Z ]*$/]',
        'error' => t('Only letters and white spaces allowed in Your Name.'
        )
      )
    ),
    '#required' => TRUE,
  );

  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('What is your e-mail?'),
    '#size' => 30,
    '#maxlength' => 30,
    '#rules' => array(
      array(
        'rule' => 'email',
        'error' => t('Invalid email format.'
        )
      )
    ),
    '#required' => TRUE,
  );

  $form['agreement'] = array(
    '#type' => 'checkbox',
    '#title' => t('I agree with <a href="#">terms and conditions</a>'),
    '#default_value' => FALSE,
    '#required' => TRUE,
  );

  $form['submitButton'] = array(
    '#type' => 'submit',
    '#value' => t('Subscribe!'),
  );

  return $form;
}

/**
 * Implements hook_form_submit().
 */
function subscription_form_submit($form, &$form_state) {
  $name = $form_state['values']['userName'];
  drupal_set_message(
    t("!name, you subscribed successfully! Congrats!", array('!name'=>$name))
  );
}
